FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY . .
#COPY DotNetCoreContactsAPI/*.csproj ./DotNetCoreContactsAPI/
RUN dotnet restore

# copy everything else and build app
#COPY DotNetCoreContactsAPI/. ./DotNetCoreContactsAPI/
WORKDIR /app/DotNetCoreContactsAPI
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2.4-alpine3.9 AS runtime
WORKDIR /app
COPY --from=build /app/DotNetCoreContactsAPI .
WORKDIR /app/DotNetCoreContactsAPI/out
ENTRYPOINT ["dotnet", "DotNetCoreContactsAPI.dll"]