FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine3.9 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "/src/DotNetCoreContactsAPI/DotNetCoreContactsAPI.csproj"
RUN dotnet publish "/src/DotNetCoreContactsAPI/DotNetCoreContactsAPI.csproj" -c Release -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2.4-alpine3.9 AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "DotNetCoreContactsAPI.dll"]